### ISSUE TITLE
IO Paint doesn't start due to missing config.json file

### ISSUE THREAD

**Issue by 6Morpheus6** [halr9000/iopaint-pinokio#1]
Hi :) Thanks for the installer.
Could you please provide a config.json or remove the config.json flag, or IO Paint won't start.

![image](https://github.com/user-attachments/assets/178fd56f-d37a-4caa-930b-86d1be1e6b48)

Without the flag in line 11 (start.js) IO Paint is starting.
```javascript
message: [
          "iopaint start",
        ],
```

**Comment by halr9000** [comment]
Next time I hack on it, I do want to improve this. I found myself annoyed at the project for how it uses config files, and got distracted thinking about ways to fix it, rather than make workarounds in pinokio. You are welcome to submit a fix @6Morpheus6 .

**Comment by 6Morpheus6** [comment]
> Next time I hack on it, I do want to improve this. I found myself annoyed at the project for how it uses config files, and got distracted thinking about ways to fix it, rather than make workarounds in pinokio. You are welcome to submit a fix @6Morpheus6 .

@halr9000 The fix is quite simple. Just remove the flag in the start file. The config isn't necessary imo. I'm using IO Paint for a while now. (Wrote my own installer once) And I never missed a function.
But sure, I can quickly fork your project and send a PR. :)

**Comment by 6Morpheus6** [comment]
@halr9000 I decided to add a config check in `pinokio.js` that detects if a config file is present and launches IO Paint accordingly.
Now it works with and without config file automatically.
Sent a PR  #2
